import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import mjml2html from 'mjml';
import sharp from 'sharp';

import {
    customerConfirmationPreview,
    escapeHtml,
    getFirstName,
    renderCustomerConfirmationBodyHtml,
} from '../functions/customerConfirmation.ts';
import {
    internalNotificationPreview,
    renderInternalNotificationMessageHtml,
} from '../functions/internalNotification.ts';

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, '..');
const outputDirectory = path.join(projectRoot, 'emails', 'dist');
const generatedModuleDirectory = path.join(projectRoot, 'functions', 'generated');
const emailAssetSourceDirectory = path.join(projectRoot, 'src', 'assets', 'email');
const publicEmailAssetDirectory = path.join(projectRoot, 'public', 'email');
const themedSignatureAssets = [
    { key: 'email', filename: 'email.png' },
    { key: 'globe', filename: 'globe.png' },
    { key: 'linkedIn', filename: 'linkedin.png' },
    { key: 'monogram', filename: 'kn-monogram.png' },
    { key: 'location', filename: 'location.png' },
];
const signatureAssetPreviewReplacements = [
    ['{{assetMonogram}}', 'https://nowakkamil.com/email/kn-monogram.png'],
    ['{{assetGlobe}}', 'https://nowakkamil.com/email/globe.png'],
    ['{{assetEmail}}', 'https://nowakkamil.com/email/email.png'],
    ['{{assetLinkedIn}}', 'https://nowakkamil.com/email/linkedin.png'],
    ['{{assetLocation}}', 'https://nowakkamil.com/email/location.png'],
    ['{{assetWave}}', 'https://nowakkamil.com/email/signature-wave.png'],
];

const customerVariant = 'customer-message-dark';
const internalVariant = 'internal-contact-notification';

const previewReplacements = [
    [/{{\s*firstName\s*}}/g, escapeHtml(getFirstName(customerConfirmationPreview.name))],
    [/{{\s*message\s*}}/g, renderCustomerConfirmationBodyHtml(customerConfirmationPreview.message)],
];

const internalPreviewReplacements = [
    [/{{\s*customerName\s*}}/g, escapeHtml(internalNotificationPreview.name)],
    [/{{\s*customerEmail\s*}}/g, escapeHtml(internalNotificationPreview.email)],
    [
        /{{\s*message\s*}}/g,
        renderInternalNotificationMessageHtml(internalNotificationPreview.message),
    ],
];

const resolveSignaturePreviewAssets = (html) => {
    let resolvedHtml = html;
    for (const [token, url] of signatureAssetPreviewReplacements) {
        resolvedHtml = resolvedHtml.replaceAll(token, url);
    }
    return resolvedHtml;
};

async function compile(mjml, sourcePath, outputName) {
    const { html, errors } = await mjml2html(mjml, {
        filePath: sourcePath,
        minify: false,
        validationLevel: 'strict',
    });

    if (errors.length > 0) {
        const details = errors
            .map(({ line, message, tagName }) => `${outputName}:${line} <${tagName}> ${message}`)
            .join('\n');
        throw new Error(`MJML compilation failed:\n${details}`);
    }

    return html;
}

async function buildVariant(variant) {
    const sourcePath = path.join(projectRoot, 'emails', `${variant}.mjml`);
    const signaturePath = path.join(projectRoot, 'emails', 'signature', 'signature.automated.html');
    const [sourceTemplate, signature] = await Promise.all([
        readFile(sourcePath, 'utf8'),
        readFile(signaturePath, 'utf8'),
    ]);
    const signatureStyleMatch = signature.match(/<style[^>]*>([\s\S]*?)<\/style>/i);
    if (!signatureStyleMatch) {
        throw new Error('Signature source must contain an embedded <style> block.');
    }

    const signatureStyles = signatureStyleMatch[1].trim();
    const signatureMarkup = signature.replace(signatureStyleMatch[0], '').trim();
    const source = sourceTemplate
        .replace('/* SIGNATURE_STYLES */', signatureStyles)
        .replace('<!-- SIGNATURE_HTML -->', signatureMarkup);

    if (source === sourceTemplate || source.includes('SIGNATURE_')) {
        throw new Error('Email source is missing its signature build placeholders.');
    }

    let previewSource = source;
    for (const [pattern, value] of previewReplacements) {
        previewSource = previewSource.replace(pattern, value);
    }
    previewSource = resolveSignaturePreviewAssets(previewSource);

    const [productionHtml, previewHtml] = await Promise.all([
        compile(source, sourcePath, `${variant}.html`),
        compile(previewSource, sourcePath, `${variant}.preview.html`),
    ]);

    await Promise.all([
        writeFile(path.join(outputDirectory, `${variant}.html`), productionHtml),
        writeFile(path.join(outputDirectory, `${variant}.preview.html`), previewHtml),
        writeFile(
            path.join(generatedModuleDirectory, `${variant}.ts`),
            `// Generated by npm run email:build. Do not edit.\nexport const customerMessageDarkHtml = ${JSON.stringify(productionHtml)};\n`,
        ),
    ]);

    console.log(`Built emails/dist/${variant}.html`);
    console.log(`Built emails/dist/${variant}.preview.html`);
    console.log(`Built functions/generated/${variant}.ts`);
}

async function buildInternalVariant() {
    const sourcePath = path.join(projectRoot, 'emails', `${internalVariant}.mjml`);
    const source = await readFile(sourcePath, 'utf8');
    let previewSource = source;

    for (const [pattern, value] of internalPreviewReplacements) {
        previewSource = previewSource.replace(pattern, value);
    }

    const [productionHtml, previewHtml] = await Promise.all([
        compile(source, sourcePath, `${internalVariant}.html`),
        compile(previewSource, sourcePath, `${internalVariant}.preview.html`),
    ]);

    await Promise.all([
        writeFile(path.join(outputDirectory, `${internalVariant}.html`), productionHtml),
        writeFile(path.join(outputDirectory, `${internalVariant}.preview.html`), previewHtml),
        writeFile(
            path.join(generatedModuleDirectory, `${internalVariant}.ts`),
            `// Generated by npm run email:build. Do not edit.\nexport const internalContactNotificationHtml = ${JSON.stringify(productionHtml)};\n`,
        ),
    ]);

    console.log(`Built emails/dist/${internalVariant}.html`);
    console.log(`Built emails/dist/${internalVariant}.preview.html`);
    console.log(`Built functions/generated/${internalVariant}.ts`);
}

async function buildSignaturePreview() {
    const signatureDirectory = path.join(projectRoot, 'emails', 'signature');
    const signaturePath = path.join(signatureDirectory, 'signature.html');
    const signature = resolveSignaturePreviewAssets(await readFile(signaturePath, 'utf8'));
    const indentedSignature = signature
        .trimEnd()
        .split('\n')
        .map((line) => (line.length > 0 ? `        ${line}` : ''))
        .join('\n');
    const preview = `<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Kamil Nowak — Email signature preview</title>
    </head>
    <body style="margin: 0; padding: 16px; background-color: #010611">
${indentedSignature}
    </body>
</html>
`;

    await writeFile(path.join(signatureDirectory, 'signature.preview.html'), preview);
    console.log('Built emails/signature/signature.preview.html');
}

const createSignatureWaveSvg = () => {
    const paths = Array.from({ length: 15 }, (_, index) => {
        const offset = index * 8;
        const opacity = Math.max(0.12, 0.72 - index * 0.035).toFixed(2);
        return `<path d="M -60 ${248 + offset} C 150 ${105 + offset}, 330 ${380 - offset}, 560 ${278 + offset / 2} S 930 ${236 + offset}, 1260 ${318 + offset / 3}" fill="none" stroke="url(#waveLine)" stroke-width="${index < 3 ? 2.2 : 1}" stroke-opacity="${opacity}"/>`;
    }).join('');
    const particles = Array.from({ length: 250 }, (_, index) => {
        const x = ((index * 83) % 1240) - 20;
        const baseY = 278 + Math.sin(x / 128) * 58 + Math.sin(x / 47) * 22;
        const spread = ((index * 47) % 150) - 75;
        const y = Math.max(90, Math.min(414, baseY + spread));
        const radius = 0.7 + ((index * 13) % 20) / 10;
        const opacity = 0.22 + ((index * 17) % 65) / 100;
        return `<circle cx="${x}" cy="${y.toFixed(1)}" r="${radius.toFixed(1)}" fill="#6eb4ff" fill-opacity="${Math.min(opacity, 0.9).toFixed(2)}"/>`;
    }).join('');

    return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="340" viewBox="0 80 1200 340">
        <defs>
            <linearGradient id="waveLine" x1="0" y1="0" x2="1" y2="0">
                <stop offset="0" stop-color="#2d7fff"/>
                <stop offset="0.42" stop-color="#7cc3ff"/>
                <stop offset="1" stop-color="#2d7fff" stop-opacity="0.24"/>
            </linearGradient>
            <filter id="glow" x="-20%" y="-80%" width="140%" height="260%">
                <feGaussianBlur stdDeviation="5" result="blur"/>
                <feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge>
            </filter>
        </defs>
        <g filter="url(#glow)">${paths}</g>
        <g>${particles}</g>
    </svg>`;
};

async function publishSignatureAssets() {
    await mkdir(publicEmailAssetDirectory, { recursive: true });
    const encodedAssets = Object.fromEntries(
        await Promise.all(
            themedSignatureAssets.map(async ({ key, filename }) => {
                const buffer = await sharp(path.join(emailAssetSourceDirectory, filename))
                    .tint({ r: 83, g: 164, b: 255 })
                    .png()
                    .toBuffer();
                await writeFile(path.join(publicEmailAssetDirectory, filename), buffer);
                return [key, buffer.toString('base64')];
            }),
        ),
    );
    const waveBuffer = await sharp(Buffer.from(createSignatureWaveSvg())).png().toBuffer();
    encodedAssets.wave = waveBuffer.toString('base64');
    await writeFile(path.join(publicEmailAssetDirectory, 'signature-wave.png'), waveBuffer);
    await writeFile(
        path.join(generatedModuleDirectory, 'email-theme-assets.ts'),
        `// Generated by npm run email:build. Do not edit.\nexport const EMAIL_THEME_ASSET_BASE64 = ${JSON.stringify(encodedAssets)} as const;\n`,
    );
    console.log('Published themed public/email assets');
    console.log('Built functions/generated/email-theme-assets.ts');
}

await Promise.all([
    mkdir(outputDirectory, { recursive: true }),
    mkdir(generatedModuleDirectory, { recursive: true }),
]);
await publishSignatureAssets();
await Promise.all([buildVariant(customerVariant), buildInternalVariant(), buildSignaturePreview()]);
